name: Build Test

on:
  push:
    branches-ignore:
      - develop
    paths-ignore:
      - '**/node_modules/**'
      - '.github/**'
      - '.github/*'
      - '.changeset/**'
  pull_request:
    paths-ignore:
      - '**/node_modules/**'
      - '.github/**'
      - '.github/*'
    branches-ignore:
      - renovate*
      - changeset-release/develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      # yarn cache
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Restore yarn cache
        uses: actions/cache@v3.0.4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            yarn-cache-folder-

      - run: yarn --immutable
      - run: yarn lint
      - run: yarn build

      - name: Get changed files in the packages folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v29.0.7
        with:
          files_ignore: |
            .changeset/**
            packages/**/package.json
            packages/**/*.{md,mdx}
            !*.md

      - name: Run __tests__ (coverage)
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          yarn rebuild
          export FORCE_COLOR=true
          export TEST_MNEMONIC=${{ secrets.TEST_MNEMONIC }}
          yarn test
